### ISSUE TITLE
Suggestion on regex improvements

### ISSUE THREAD

**Issue by hbtalha** [David-Else/simple-youtube-chapter-extractor#3]
The current regex won't capture the chapters for this video for example:
https://www.youtube.com/watch?v=Dorf8i6lCuk

[I have written a media player](https://github.com/hbtalha/QThisPlayer) that parses the text containing chapter information and displays the chapter and from my experiences I noticed that YouTube just removes the timestamps regex from the string and whatever is left is used as the chapter title after some tweaks.
For example this text in the descriptions: 
```
#2*\+  Wh#at# is\ Re#act*00:00 sdds#
#3 First React Code 01:15sdsdd
```
 generates the following chapters
![image](https://user-images.githubusercontent.com/49079799/140647105-01e006fb-7910-475b-ad77-66f6ff8d2cb5.png)

I am currently updating my chapters capturing function to behave like above. I am thinking about removing the regex below to remove the timestamps from the string containing a chapter:
`/([^a-zA-Z0-9_](?:(\d{2}):)?(\d{2}):(\d{2}))/gm` (still a WIP)

Edit: I have come up with a way to extract the chapter title and its timestamp based on the experiences I made with YouTube chapters:
Qt C++ code:
```
int main(int argc, char *argv[])
{
    QCoreApplication a(argc, argv);

    QString str = "#2 (00:10:00) variables ✘";
    str.prepend(' ');  // force timestamp capture when they are at the beginning of the string
    QRegularExpression re("(?:[^a-zA-Z0-9_=:])((?:(\\d{1,2}):)?(\\d{1,2}):(\\d{1,2}))(?:[^a-zA-Z0-9_=:])?");
    QRegularExpression deletionRE("^[^a-zA-Z0-9!'\"_`\\[{(\\?]*|[^a-zA-Z0-9!)'\"_`}\\]\\.\\?]*$");
    QRegularExpressionMatch match = re.match(str);

    if(match.hasMatch())
    {
        qDebug() << "Match:" << match.captured(1);
        qDebug() << "Hour:" << match.captured(2);
        qDebug() << "Minute:" << match.captured(3);
        qDebug() << "Second:" << match.captured(4);

        qDebug() << "part1:" << str.mid(0, str.indexOf(match.captured(1)));
        qDebug() << "part2:" << str.mid(str.lastIndexOf(match.captured(1)) + match.captured(1).size(), str.size() - 1);
        QString part1 = str.mid(0, str.indexOf(match.captured(1)));
        QString part2 = str.mid(str.lastIndexOf(match.captured(1)) + match.captured(1).size(), str.size() - 1);

        str.remove(match.captured(1));
        part1.remove(deletionRE);
        part2.remove(deletionRE);

        QString chapterTitle;
        if(! part1.isEmpty() && ! part2.isEmpty())
        {
            chapterTitle =   part1 + "." + part2;
        }
        else
        {
            chapterTitle = part1.isEmpty() ? part2 : part1;
        }

        chapterTitle.remove(deletionRE);

        qDebug() << "Chapter Title" << chapterTitle;
    }

}
```
Output:
```
Match: "00:10:00"
Hour: "00"
Minute: "10"
Second: "00"
part1: " #2 ("
part2: ") variables ✘"
Chapter Title "2.variables"
```

**Comment by David-Else** [comment]
Thanks for this info, your player looks great.

My plan with simple-youtube-chapter was to eventually use the meta-data supplied by youtube-dl when they fixed the bugs. It seems to work now with [yt-dlp](https://github.com/yt-dlp/yt-dlp/)

```
yt-dlp --embed-metadata [URL]
```
What do you think? It seems to work in MPV, but I have not tested on many videos yet.

**Comment by hbtalha** [comment]
I have downloaded some videos(short ones) and it seems to work great in VLC.
I didn't know that this feature in yt-dlp embeds chapters too, great to know it.

To test it more, you can upload your own test video to YouTube and add chapters timestamps in many formats and see what happens when you download it with yt-dlp.

Edit: if your goal is to only add chapters, wouldn't
```
yt-dlp --embed-chapters [URL]
```
be a more suitable option?

**Comment by David-Else** [comment]
Cheers, I didn't spot `yt-dlp --embed-chapters [URL]`.

**Comment by David-Else** [comment]
Added yt-dlp to FAQ
